services:
  db:
    image: mysql:8.0
    container_name: Dozentenverwaltung_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: Dozentenverwaltung
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: Dozentenverwaltung_server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=mysql
      - DB_PASSWORD=12345678
      - DB_NAME=Dozentenverwaltung
      - DB_PORT=3306
      - NODE_ENV=production
volumes:
  db_data:
